env:
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - ObjectExpression: first
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
